In [1]:
import pandas as pd
import numpy as np

In [9]:
# Шаг 1 - выгрузка информации о продажах
df = pd.read_csv('/Users/mikhailstroganov/project_tms2/blinkit_orders.csv')
df

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,UPI,29940,6128
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588

In [10]:
df['promised_delivery_time'] = pd.to_datetime(df['promised_delivery_time'])
df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'])
df['order_date'] = pd.to_datetime(df['order_date'])
df['order_dt'] = df['order_date'].dt.date
df

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,order_dt
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771,2024-07-17
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534,2024-05-28
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886,2024-09-23
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917,2023-11-24
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741,2023-11-20
...,...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587,2023-12-25
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458,2023-11-27
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424,2024-06-21
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,UPI,29940,6128,2024-06-06
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588,2023-08-23

In [ ]:
# Шаг 2 - (консультация с заказчиком) выполнение подсчетов согласно техническому заданию

# Метрики: кол-во заказов в день, сумма продаж в день, распределение выручки по payment_method

df_gr = df.groupby('order_dt', as_index=False).agg({'order_id':'count', 'order_total':'sum'})
df_piv = df.pivot_table(index=['order_dt'], columns=['payment_method'], values=['order_total'], aggfunc=['sum']).fillna(0)

                       sum
               order_total
payment_method        Card     Cash      UPI   Wallet
order_dt
2023-03-16         3128.67  3536.51  5114.45  4286.41
2023-03-17         4923.75   646.54     0.00  5248.36
2023-03-18         4269.44  5527.56  5408.36  3370.17
2023-03-19         8165.05  2266.96     0.00  4782.10
2023-03-20         1664.01  4549.72  1650.30  3448.71
...                    ...      ...      ...      ...
2024-10-31         6795.22  4196.09  6743.25  7955.39
2024-11-01         5163.73  4885.03  2598.47  2133.80
2024-11-02         3138.06  7656.49     0.00     0.00
2024-11-03         4724.39  6610.97  9844.30  7582.29
2024-11-04            0.00  4981.16  3260.56  5578.40

[600 rows x 4 columns]

In [16]:
# шаг 3 - выгрузка Excel-файла

df_gr.to_excel('/Users/mikhailstroganov/project_tms2/blinkit1.xlsx', index=False)
df_piv.to_excel('/Users/mikhailstroganov/project_tms2/blinkit2.xlsx')

In [ ]:
writer = pd.ExcelWriter("blinkit.xlsx")

df_gr.to_excel(writer, sheet_name="Динамика продаж 2 ")
df_piv.to_excel(writer, sheet_name="Распределение продаж 2")

writer.close()